### ISSUE TITLE
[Question] About multiple Service and Validator in one Controller.

### ISSUE THREAD

**Issue by bs135** [NonFactors/MVC5.Template#5]
Hi,

Thank you for this open source. I am trying to use it.
I have a question. How do I use two or more Services and Validators in one Controller?

**Comment by Muchiachio** [comment]
You can inject more services and validators to your controller's constructor if they are registered in a DI.
Be careful though, because by setting services and validators by hand you can miss initialization boilerplate code needed for services and validators to work correctly, which happens in [serviced](https://github.com/NonFactors/MVC5.Template/blob/develop/src/MvcTemplate.Controllers/ServicedController.cs) and [validated](https://github.com/NonFactors/MVC5.Template/blob/develop/src/MvcTemplate.Controllers/ValidatedController.cs) controllers.
```C#
public HomeController : BaseController
{
    private IAService AService { get; set; }
    private IBService BService { get; set; }

    private IAValidator AValidator { get; set; }
    private IBValidator BValidator { get; set; }

    public HomeController(IAService aService, IAValidator aValidator,
        IBService bService, IBValidator bValidator)
    {
        // Setter code
    }
}

public class MainContainer : ServiceContainer
{
    public void RegisterServices()
    {
        // Other code

        Register<IAService, AService>();
        Register<IBService, BService>();

        Register<IAValidator, AValidator>();
        Register<IBValidator, BValidator>();
    }
}
```

**Comment by bs135** [comment]
thank you so much.
